word_list = [
    "HOMELANDER", "THOR", "IRONMAN", "BUTCHER", "HULK", "GROOT", "BATMAN", "JOKER",
    "SUPERMAN", "WONDERWOMAN", "FLASH", "AQUAMAN", "CYBORG", "SPIDERMAN", "VENOM",
    "LOKI", "THANOS", "VISION", "SCARLETWITCH", "QUICKSILVER", "BLACKWIDOW", "HAWKEYE",
    "DOCTORSTRANGE", "BLACKPANTHER", "CAPTAINAMERICA", "WINTERSOLDIER", "FALCON",
    "ANTMAN", "WASP", "STARLORD", "GAMORA", "DRAX", "ROCKET", "GROOT", "MANTIS",
    "NEBULA", "YONDU", "RAVAGER", "SHURI", "OKOYE", "NIGHTWING", "ROBIN", "REDHOOD",
    "BATGIRL", "CATWOMAN", "PENGUIN", "RIDDLER", "TWOFACE", "SCARECROW", "BANE"
]
